# Generated by Django 5.2.6 on 2025-09-17 01:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Sepatu Bola'), ('ball', 'Bola'), ('accessories', 'Aksesori'), ('equipment', 'Perlengkapan'), ('training', 'Peralatan Latihan')], max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('brand', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
